version: '3'
services:
  db:
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD= ${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - /mnt/c/Users/Admin/Desktop/postgresql_data:/var/lib/postgresql/data
  geoserver:
    image: docker.osgeo.org/geoserver:2.21.1
    ports:
      - "8080:8080"
    volumes:
      - /mnt/c/Users/Admin/Desktop/geoserverdata:/opt/geoserver/data_dir