version: '3.7'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  geoserver:
    image: docker.osgeo.org/geoserver:2.21.1
    environment:
      JAVA_OPTS: -Duser.timezone=UTC
    volumes:
      - geoserver_data:/opt/geoserver_data
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  geoserver_data: